site_name: Jessim Daniel Virgil

nav:
  - Home: index.md
  - About: about.md
  - Utils: utils.md
  - Jessim : jessim.md
  - Virgil : virgil.md
  - Daniel : daniel.md
  # test 2
  
theme:
  name: 'material'
